version: "3.7"
services:

  postgres:
    image: postgres:14.7
    env_file:
      - app/config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - my_network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - cache:/data
    networks:
      - my_network

  app:
    restart: unless-stopped
    image: app_image
    build:
      context: .
    env_file:
      - app/config/.env
    depends_on:
      - postgres
      - redis
    networks:
      - my_network

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"172.17.0.0/16\", \"192.168.0.10\"]"
    depends_on:
      - app
      - postgres
      - redis
    networks:
      - my_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - my_network

volumes:
  cache:
    driver: local

networks:
  my_network:
    driver: bridge